workflows:
  ios-simulator-preview:
    name: iOS Simulator App Preview
    max_build_duration: 60

    environment:
      flutter: 3.32.7

    scripts:
      - name: Show Flutter version
        script: |
          flutter --version

      - name: Disable Swift Package Manager
        script: |
          flutter config --no-enable-swift-package-manager

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build iOS Simulator App (.app)
        script: |
          flutter build ios \
            --simulator \
            --debug \
            --no-codesign

      - name: Show output
        script: |
          ls -lh build/ios/iphonesimulator/

    artifacts:
      - build/ios/iphonesimulator/*.app
      - build/ios/iphonesimulator/Runner.app
